USE Curso
GO
--N CONVIERTE EL TEXTO EN NVARCHA
--U USER DESINED TABLE
IF OBJECT_ID(N'Curso.dbo.Alumno', N'U') IS NULL
BEGIN
-- Creamos la tabla
CREATE TABLE dbo.Alumno
(

id [INT] NOT NULL IDENTITY PRIMARY KEY,
Dni [NVARCHAR](10) NOT NULL,
Nombre [NVARCHAR](50) NOT NULL,
Apellidos [NVARCHAR](50) NOT NULL,
Edad [INT] NOT NULL,
Nacimiento [DATETIME] NOT NULL,
Registro [DATETIME] NOT NULL,
RowGuid [UNIQUEIDENTIFIER] NOT NULL
)
END
